# Generated by Django 4.2.5 on 2025-09-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
